# Generated by Django 3.1.7 on 2021-03-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=2500, verbose_name='Сообщение')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
