# Generated by Django 3.1.7 on 2021-03-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='images/gallery')),
            ],
            options={
                'verbose_name': 'галерея',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Введите адрес, для товара. Адрес не может состоять из русский букв и символов, которые не поддерживаются браузерами', max_length=150, unique=True)),
                ('description', models.CharField(help_text='Будет показано на странице номера', max_length=150, verbose_name='Описание')),
                ('short_description', models.CharField(help_text='Будет показано на карточке номера', max_length=50, verbose_name='Краткое описание')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер команты')),
                ('beds', models.PositiveSmallIntegerField(verbose_name='Количество кроватей')),
                ('features', models.CharField(help_text='Например - беспроводной интернет и телевизор', max_length=75, verbose_name='Особенности')),
                ('poster', models.ImageField(null=True, upload_to='images/poster/', verbose_name='Картинка для карточки')),
            ],
            options={
                'verbose_name': 'команата',
                'verbose_name_plural': 'команаты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/roomImages')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='room_image', to='mainapp.room')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
