# Generated by Django 3.1.7 on 2021-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'галерея', 'verbose_name_plural': 'галерею'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'комната', 'verbose_name_plural': 'комнаты'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='text',
            field=models.CharField(default='Напишите пару слов...', help_text='Текст будет поверх картинки', max_length=30, verbose_name='Текст на картинке'),
        ),
    ]
