# Generated by Django 3.1.7 on 2021-03-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210320_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'комнату', 'verbose_name_plural': 'комнаты'},
        ),
    ]
