# Generated by Django 3.1.7 on 2021-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(help_text='Будет показано на странице номера', verbose_name='Описание'),
        ),
    ]
