# Generated by Django 3.1.7 on 2021-03-27 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210325_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
