# Generated by Django 3.1.7 on 2021-03-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210314_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
    ]
